#Posterior Predictive Simulation (PPS) adequacy testing using among-character
#variance in state frequency as the test statistic (Wagner 2012).

#functions:
#CharacterVariance()    - Computes the among-character variance in state frequency for a nexus matrix; the PPS test statistic.
#ReadPPSDatasets()      - Reads a set of nexus files generated by RevBayes ppsample.Rev from posterior draws.
#PPSPValue()            - One-tailed p-value: proportion of PPS replicates with test statistic >= observed value.
#IsAdequate()           - Returns TRUE if PPSPValue() > 0.05 (model is not significantly worse than a perfect fit).
#PPSForReplicate()      - Top-level wrapper: runs PPS check for one simulation replicate under a named model.
#PPSAdequacyRates()     - Aggregates IsAdequate() across the full grid, returning proportion-adequate per model.



#' Compute among-character variance in state frequency
#'
#' The test statistic is the variance across characters of the proportion of
#' tips scored as state 0 (Wagner 2012 eq. 1). Ambiguous/missing positions
#' ("?" or "-") are excluded from each character's frequency calculation.
#'
#' @param nexPath  Path to a nexus file (observed or PPS replicate).
#' @return Scalar numeric: among-character variance in state-0 frequency,
#'   or NA if the file cannot be read or has no parseable characters.
#' @importFrom ape read.nexus.data
#' @export
CharacterVariance <- function(nexPath) {
  if (!file.exists(nexPath)) {
    warning("Nexus file not found: ", nexPath)
    return(NA_real_)
  }

  mat <- tryCatch(
    do.call(rbind, ape::read.nexus.data(nexPath)),
    error = function(e) {
      warning("Could not read nexus file: ", nexPath, " — ", conditionMessage(e))
      return(NULL)
    }
  )

  if (is.null(mat) || ncol(mat) == 0L) return(NA_real_)

  # Per-character proportion of tips in state "0", ignoring ambiguities
  char_freq0 <- apply(mat, 2, function(col) {
    coded <- col[!col %in% c("?", "-")]
    if (length(coded) == 0L) return(NA_real_)
    sum(coded == "0") / length(coded)
  })

  char_freq0 <- char_freq0[!is.na(char_freq0)]
  if (length(char_freq0) < 2L) return(NA_real_)

  var(char_freq0)
}

#' Read PPS nexus datasets generated by RevBayes ppsample.Rev
#'
#' PPS datasets are written to a directory with names matching a common
#' prefix followed by an integer index (e.g. "pps_0001.nex"). This function
#' lists all matching files and returns their paths in sorted order.
#'
#' @param ppsDir   Directory containing PPS nexus files.
#' @param pattern  Regex pattern for PPS file names
#'                 (default "^pps_.*\\.nex$").
#' @return Character vector of absolute file paths, or character(0) if none
#'   are found.
#' @export
ReadPPSDatasets <- function(ppsDir,
                            pattern = "^pps_.*\\.nex$") {
  if (!dir.exists(ppsDir)) {
    warning("PPS directory not found: ", ppsDir)
    return(character(0))
  }
  sort(list.files(ppsDir, pattern = pattern, full.names = TRUE))
}

#' Compute PPS p-value for one observed matrix
#'
#' The p-value is the proportion of PPS replicates whose test statistic
#' (CharacterVariance) is greater than or equal to the observed value.
#' One-tailed because the alternative is that the model produces *less*
#' variance than the data (under-dispersion indicating poor fit).
#'
#' @param observedVar  Observed CharacterVariance() value.
#' @param ppsVars      Numeric vector of CharacterVariance() values from PPS
#'                     replicates.
#' @return Scalar p-value in [0, 1], or NA if ppsVars is empty.
#' @export
PPSPValue <- function(observedVar, ppsVars) {
  ppsVars <- ppsVars[!is.na(ppsVars)]
  if (length(ppsVars) == 0L || is.na(observedVar)) return(NA_real_)
  mean(ppsVars >= observedVar)
}

#' Test whether a model is adequate
#'
#' A model is considered adequate (not significantly worse than a perfect fit)
#' if PPSPValue() > 0.05. The threshold is one-sided: we reject only when
#' the model systematically *under-produces* among-character variance.
#'
#' @param pValue  Scalar p-value from PPSPValue().
#' @param alpha   Significance threshold (default 0.05).
#' @return Logical TRUE if adequate, FALSE if not, NA if pValue is NA.
#' @export
IsAdequate <- function(pValue, alpha = 0.05) {
  if (is.na(pValue)) return(NA)
  pValue > alpha
}

#' Run PPS adequacy check for one replicate under one model
#'
#' Reads the observed nexus matrix and all PPS nexus datasets produced by
#' RevBayes for that replicate, computes CharacterVariance() for each,
#' then returns IsAdequate() together with supporting diagnostics.
#'
#' @param scenario   "nt" or "mk".
#' @param gridTag    Grid tag string from GridTag().
#' @param repID      Replicate ID e.g. "sim001".
#' @param modelID    Model script name e.g. "model4".
#' @param partition  Nexus partition to evaluate: "neo" or "trans"
#'                   (default "neo").
#' @param alpha      Adequacy threshold (default 0.05).
#' @return Named list:
#'   \item{adequate}{Logical result of IsAdequate().}
#'   \item{p.value}{PPS p-value.}
#'   \item{observed_var}{CharacterVariance() of the observed matrix.}
#'   \item{pps_vars}{Numeric vector of PPS CharacterVariance() values.}
#'   \item{n_pps}{Number of valid PPS datasets used.}
#' @export
PPSForReplicate <- function(scenario, gridTag, repID, modelID,
                            partition = c("neo", "trans"),
                            alpha     = 0.05) {
  partition <- match.arg(partition)
  simDir    <- SimDirAbs(scenario, gridTag, repID)

  # Observed matrix
  obsFile    <- file.path(simDir, paste0(partition, ".nex"))
  obsVar     <- CharacterVariance(obsFile)

  # PPS datasets directory: modelID/pps/ within the sim directory
  ppsDir     <- file.path(simDir, modelID, "pps")
  ppsFiles   <- ReadPPSDatasets(ppsDir)

  ppsVars <- vapply(ppsFiles, CharacterVariance, numeric(1))
  pVal    <- PPSPValue(obsVar, ppsVars)

  list(
    adequate     = IsAdequate(pVal, alpha),
    p.value      = pVal,
    observed_var = obsVar,
    pps_vars     = ppsVars,
    n_pps        = sum(!is.na(ppsVars))
  )
}

#' Aggregate PPS adequacy rates across the full parameter grid
#'
#' Calls PPSForReplicate() for every (gridTag, repID) combination under a
#' given model and returns the proportion of replicates for which the model
#' is adequate, per grid cell.
#'
#' @param modelID    Model script name.
#' @param scenario   "nt" or "mk" (default "nt").
#' @param partition  "neo" or "trans" (default "neo").
#' @param grid       Parameter grid data frame (default PARAM_GRID).
#' @param nRep       Replicates per cell (default N_REP).
#' @param alpha      Adequacy threshold (default 0.05).
#' @return Data frame with columns: scenario, gridTag, modelID, partition,
#'   prop_adequate, n_adequate, n_total.
#' @export
PPSAdequacyRates <- function(modelID,
                             scenario  = "nt",
                             partition = c("neo", "trans"),
                             grid      = PARAM_GRID,
                             nRep      = N_REP,
                             alpha     = 0.05) {
  partition <- match.arg(partition)

  rows <- vector("list", nrow(grid))

  for (gi in seq_len(nrow(grid))) {
    gridTag  <- GridTag(grid[gi, ])
    adequate <- vapply(seq_len(nRep), function(rep) {
      repID <- SimID(rep)
      res   <- tryCatch(
        PPSForReplicate(scenario, gridTag, repID, modelID,
                        partition = partition, alpha = alpha),
        error = function(e) {
          warning("PPSForReplicate failed: ", conditionMessage(e))
          list(adequate = NA)
        }
      )
      res$adequate
    }, logical(1))

    rows[[gi]] <- data.frame(
      scenario      = scenario,
      gridTag       = gridTag,
      modelID       = modelID,
      partition     = partition,
      prop_adequate = mean(adequate, na.rm = TRUE),
      n_adequate    = sum(adequate  %in% TRUE),
      n_total       = sum(!is.na(adequate)),
      stringsAsFactors = FALSE
    )
  }

  do.call(rbind, rows)
}
