# PPS.R
# NEW file for nt-sim project.
#
# Posterior Predictive Simulation (PPS) adequacy testing using among-character
# variance in state frequency as the test statistic (Wagner 2012).
#
# Key functions to implement:
#   CharacterVariance()    - Computes the among-character variance in state
#                            frequency for a nexus matrix; the PPS test statistic.
#   ReadPPSDatasets()      - Reads a set of nexus files generated by RevBayes
#                            ppsample.Rev from posterior draws.
#   PPSPValue()            - One-tailed p-value: proportion of PPS replicates
#                            with test statistic >= observed value.
#   IsAdequate()           - Returns TRUE if PPSPValue() > 0.05 (model is not
#                            significantly worse than a perfect fit).
#   PPSForReplicate()      - Top-level wrapper: runs PPS check for one simulation
#                            replicate under a named model.
#   PPSAdequacyRates()     - Aggregates IsAdequate() across the full grid,
#                            returning proportion-adequate per model.
#
# Adapts the supervisor's Analyses.R PPS framework, redirecting from empirical
# to simulated nexus files. Uses ppsample.Rev, ppsim_ns_n_ki.Rev, and
# ppsim_by_n_ki.Rev unchanged.
#
# Used in: analysis/07_pps.R
# Dissertation sections: 5.3 Advanced / 6.1 PPS adequacy
